import type { Metadata } from "next";
import "./globals.css";
import {
  Urbanist,
  Source_Code_Pro,
  Funnel_Display,
  Fira_Code,
  Spline_Sans,
  Outfit,
  DM_Sans,
  DM_Mono,
} from "next/font/google";

const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });

const source_code_pro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-scp",
});
const funnel = Funnel_Display({
  subsets: ["latin"],
  variable: "--font-funnel",
});

const fira = Fira_Code({ subsets: ["latin"], variable: "--font-fira" });

const spline = Spline_Sans({ subsets: ["latin"], variable: "--font-spline" });

const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

const dmsans = DM_Sans({ subsets: ["latin"], variable: "--font-dmsans" });

const dmcode = DM_Mono({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-dmcode",
});

export const metadata: Metadata = {
  title: "Jared Mabanglo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <script
          src="https://kit.fontawesome.com/a2769b4633.js"
          crossOrigin="anonymous"
        ></script>
        <script src="three.r134.min.js"></script>
      </head>
      <body
        className={`${urbanist.variable} ${source_code_pro.variable} ${funnel.variable} ${fira.variable} ${dmsans.variable} ${dmcode.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
